### PR TITLE
Spellchecked the documentation.

### PR DESCRIPTION
**Pull request by Adeon18**
This is my first pull request to an open source project and I tried to be a bit useful :)

Changes:
- Checked the entire documentation for spelling mistakes and errors.
- Removed corrupted symbols.
- Rephrased some explanations.

### CODE REVIEW

**Review by B-R-P — APPROVED** [review]
Great Work 👍

**Comment by B-R-P** [comment]
Join in [Discord](https://discord.gg/3nDwppur5S), [Reddit](https://www.reddit.com/r/LangTrans/) or [Google Groups](https://groups.google.com/g/langtrans-community)

**Comment by Adeon18** [comment]
Btw, does your repo participate in HacktoberFest 2021? :)

**Comment by B-R-P** [comment]
Let's chat in [Telegram](https://t.me/bijinpanicker)

**Pull request merged**
